name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tests repo (this repo)
        uses: actions/checkout@v3

      - name: Checkout Flask app repo (to test against)
        run: git clone https://github.com/schr95/todoism.git

      - name: Set up Python for Flask app
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flask app dependencies
        run: |
          cd todoism
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          cd todoism
          source venv/bin/activate
          flask initdb
          flask translate compile
          nohup flask run > flask.log 2>&1 &

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright dependencies (in this repo)
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test todolist.spec.ts

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
